---
- hosts: default

  remote_user: '{{ user_with_remote_access }}'

  tasks:
  - name: 'Hello World: set facts'
    set_fact:
      title: 'Hello World'

  - name: '{{ title }}: create dirs'
    become: yes
    ansible.builtin.file:
      dest: '/apps'
      owner: '{{ deploy_user }}'
      group: '{{ deploy_user }}'
      state: directory

  - name: '{{ title }}: unset facts'
    set_fact:
      title:
